version = "0.3.2"

# This loads the env file into the environment of bonnie and the executed child process 
# You may need to use the following syntax to interpolate env vars in a bonnie command itself: 
# scriptName.cmd = "command for script with %EXACT_ENV_VAR_NAME for evn var interpolation"
# scriptName.env_vars = ["EXACT_ENV_VAR_NAME"]
# see https://github.com/arctic-hen7/bonnie/wiki/Environment-Variables
env_files = [".env"]

[scripts]
    # This would be nice!!!
    # start.cwd = "playground"
    start.cmd = [
        "pushd playground",
        "deno run --allow-net --unstable ../main.ts",
        "popd",
    ]

    build = [
        "bonnie bundle",
        # "bonnie compile"
    ]
    bundle.cmd = "deno bundle --unstable main.ts dist/%APP_NAME.js"
    bundle.env_vars = ["APP_NAME"]

    # If needed, adjust and activate
    # compile = "deno compile --unstable --target x86_64-pc-windows-msvc --allow-read --allow-write --allow-net --allow-run -o dist/%APP_NAME main.ts "
